// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://achfiqgwprefmlhjoanj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFjaGZpcWd3cHJlZm1saGpvYW5qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE1MTM1NTAsImV4cCI6MjA1NzA4OTU1MH0.stGbQi5HDIQT-fNDfRVMqUzrFmt10xi3vkQCFpnDPEA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);