// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vjerwqqhcedemgfgfzbg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZqZXJ3cXFoY2VkZW1nZmdmemJnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE0Mjg2NzIsImV4cCI6MjA1NzAwNDY3Mn0.zOcE-5pn_FEMYErg5up6BPsHwI3SBVPXAXoKb7ZJK20";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);